#ddev-generated
services:
  web:
    environment:
      VIRTUAL_HOST: api.${DDEV_SITENAME}.ddev.site
  laravel-front:
    container_name: ddev-${DDEV_SITENAME}-laravel-front
    build:
      context: node
      args:
        gid: ${DDEV_GID}
        uid: ${DDEV_UID}
        package_manager: ${PACKAGE_MANAGER:-npm}
    environment:
      HAS_REVERB: ${HAS_REVERB:-false}
      PACKAGE_MANAGER: ${PACKAGE_MANAGER:-npm}
      VIRTUAL_HOST: ${DDEV_SITENAME}.ddev.site
      HTTP_EXPOSE: 3000:3000
      HTTPS_EXPOSE: 443:3000
      API_URL: https://api.${DDEV_SITENAME}.ddev.site
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "${DDEV_APPROOT}/front:/app"
